codemod-com/codemod-registry

codemods/jscodeshift/react-redux/8/add-state-type/index.ts
codemods/jscodeshift/react-redux/8/add-state-type/test.ts

https://linear.app/intuita/issue/INT-391/create-a-migration-to-add-the-state-type-for-mapstatetoprops-and

Add the State type for mapStateToProps and mapDispatchToProps functions

---

codemods/jscodeshift/next/13/remove-get-static-props/config.json
codemods/jscodeshift/next/13/remove-get-static-props/index.ts
codemods/jscodeshift/next/13/remove-get-static-props/test.ts
sets/next_13/config.json

https://linear.app/intuita/issue/INT-439/implement-the-remove-static-get-props-codemod

INT-439 Implement the remove-static-get-props codemod

---

codemods/ts-morph/next/13/replace-next-head/index.ts
codemods/ts-morph/next/13/replace-next-head/test.ts

Fix empty lines

---

build.ts
codemods/jscodeshift/next/13/built-in-next-font/README.md
codemods/jscodeshift/next/13/comment-deletable-files/README.md
codemods/jscodeshift/next/13/move-css-in-js-styles/README.md
codemods/jscodeshift/next/13/new-image-experimental/README.md
codemods/jscodeshift/next/13/new-link/README.md
codemods/jscodeshift/next/13/next-image-to-legacy-image/README.md
codemods/jscodeshift/next/13/remove-get-static-props/README.md
codemods/repomod-engine/next/13/app-directory-boilerplate/README.md

Changes:
* add headers to README.md files
* use prettier formatting in these files
* emit app directory boilerplate README.md

INT-1129 add headers to README.md + emit app directory boilerplate README.md

---

codemods/ts-morph/next/13/replace-next-head/index.ts
codemods/ts-morph/next/13/replace-next-head/test.ts

- adds metadata allowlist 
- bugfix
- support all basic metadata according to https://github.com/vercel/next.js/blob/a2c27aab1cec1483db5f0dd9dec8dcad629dd61d/packages/next/src/lib/metadata/generate/basic.tsx#L6

add allowlist, bugfixes

---

next/13/remove-get-static-props/index.ts
next/13/remove-get-static-props/test.ts

- handles case when the Page component is an arrow function
- handles case when Page component props are not destructured
- handles case when page component has implicit return

fix-data-fetching-function-not-injected

---

next/13/replace-next-head/index.ts
next/13/replace-next-head/test.ts

https://linear.app/intuita/issue/INT-1413/[codemodfn]-replace-next-head-structured-properties

support openGraph structured props

---

next/13/replace-next-head/index.ts
next/13/replace-next-head/test.ts

https://linear.app/intuita/issue/INT-1415/[codemodfn]-replace-next-head-support-article-type

support openGraph article type metadata

---

.prettierignore
next/13/replace-next-head-repomod/README.md
next/13/replace-next-head-repomod/index.ts
next/13/replace-next-head-repomod/test.ts

fixes https://linear.app/intuita/issue/INT-1439/merge-metadata

merge metadata

---

build.ts

1. write `index.cjs` files in the build directory
2. do not tar the gzipped cjs files

INT-1421 do not tar the gzipped cjs files

---

next/13/replace-next-router/index.ts
next/13/replace-next-router/test.ts

- Run next router codemod on [cal.com](http://cal.com/) repo at the root
- Apply every change and then search if "next/router"; import still exists

INT-1499 Next router codemod improvement 2

---

next/13/replace-next-router/index.ts

i should actually remove usesRouter.set(() => false); here; Should not explicitly set it to false; i just need to return here

INT-1499 follow-up

---

next/13/replace-next-head-v2/index.ts
next/13/replace-next-head-v2/test.ts

https://linear.app/intuita/issue/INT-1450/resolve-identifiers-that-comes-from-props

detect identifiers that are coming from component props

---

next/13/replace-next-head-v2/index.ts
next/13/replace-next-head-v2/test.ts

https://linear.app/intuita/issue/INT-1450/resolve-identifiers-that-comes-from-props

add a variable declaration when props value is jsxExpression

---

next/13/remove-get-static-props/index.ts
next/13/remove-get-static-props/test.ts

https://linear.app/intuita/issue/INT-1551/if-a-page-implements-getstaticprops-we-add-export-const-dynamic-=

add dynamic='force-static' when page implements getStaticProps

---

ember/5/no-implicit-this/test.ts

ref to tests: https://github.com/ember-codemods/ember-no-implicit-this-codemod/tree/master/transforms/no-implicit-this/__testfixtures__

INT-1740 Add the remaining tests for Ember "no-implicit-this" codemod

---

ember/5/array-wrapper/config.json
ember/5/array-wrapper/index.js
ember/5/array-wrapper/test.ts

https://github.com/ember-codemods/ember-3x-codemods/tree/master/transforms/array-wrapper

INT-1740 ember: array-wrapper

---

ember/5/app-controller-router-props/config.json
ember/5/app-controller-router-props/index.js
ember/5/app-controller-router-props/test.ts

https://linear.app/intuita/issue/INT-1740/[codemod-registry]-import-emberjs-codemods

INT-1740 Ember `app-controller-router-props` codemod

---

ember/5/cp-property-map/index.js
ember/5/cp-property-map/test.ts

https://github.com/ember-codemods/ember-3x-codemods/tree/master/transforms/cp-property-map

INT-1740 ember: cp-property-map

---

next/13/app-directory-boilerplate/index.ts

The benefit is one indentation less and more order / collapsing within the editor.

INT-1550 move handleFile and handleData function to the file scope

---

ember/5/app-controller-router-props/README.md
ember/5/array-wrapper/README.md
ember/5/cp-property-map/README.md
ember/5/cp-property/README.md
ember/5/cp-volatile/README.md
ember/5/deprecate-merge/README.md
ember/5/deprecate-router-events/README.md
ember/5/ember-jquery-legacy/README.md
ember/5/fpe-computed/README.md
ember/5/fpe-observes/README.md
ember/5/fpe-on/README.md
ember/5/jquery-apis/README.md
ember/5/jquery-event/README.md
ember/5/no-implicit-this/README.md
ember/5/notify-property-change/README.md
ember/5/object-new-constructor/README.md
react/prop-types-typescript/README.md

For the following codemods
and `no-implicit-this` codemod

INT-1755 Ember.js codemod docs

---

ember/5/app-controller-router-props/index.js
ember/5/array-wrapper/index.js
ember/5/cp-property-map/index.js
ember/5/cp-property/index.js
ember/5/cp-volatile/index.js
ember/5/deprecate-merge/index.js
ember/5/deprecate-router-events/index.js
ember/5/ember-jquery-legacy/index.js
ember/5/fpe-computed/index.js
ember/5/fpe-observes/index.js
ember/5/fpe-on/index.js
ember/5/jquery-apis/index.js
ember/5/jquery-event/index.js
ember/5/no-implicit-this/index.js
ember/5/notify-property-change/index.js
ember/5/object-new-constructor/index.js
package.json
pnpm-lock.yaml

original PR -> https://github.com/intuita-inc/codemod-registry/pull/199
was not merged into `main` successfully

INT-1740 Remove codemod cli

---

ember/5/app-controller-router-props/README.md
ember/5/array-wrapper/README.md
ember/5/cp-property-map/README.md
ember/5/cp-property/README.md
ember/5/cp-volatile/README.md
ember/5/deprecate-merge/README.md
ember/5/deprecate-router-events/README.md
ember/5/ember-jquery-legacy/README.md
ember/5/fpe-computed/README.md
ember/5/fpe-observes/README.md
ember/5/fpe-on/README.md
ember/5/jquery-apis/README.md
ember/5/jquery-event/README.md
ember/5/no-implicit-this/README.md
ember/5/notify-property-change/README.md
ember/5/object-new-constructor/README.md

ref: https://github.com/ember-codemods/directory

INT-1755 Add Applicability Criteria for ember js codemods

---

ember/5/ember-jquery-legacy/README.md
ember/5/jquery-event/README.md
ember/5/notify-property-change/README.md

1. notify-property-change
- https://deprecations.emberjs.com/v3.x/#toc_use-notifypropertychange-instead-of-propertywillchange-and-propertydidchange
2. jquery-event
- https://deprecations.emberjs.com/v3.x/#toc_jquery-event
3. ember-jquery-legacy
- https://deprecations.emberjs.com/v3.x/#toc_jquery-event

INT-1755 Write descriptions for ember.js notify-property-change, jquery-event, ember-jquery-legacy

---

ember/5/app-controller-router-props/README.md
ember/5/array-wrapper/README.md
ember/5/cp-property-map/README.md
ember/5/cp-property/README.md
ember/5/cp-volatile/README.md
ember/5/deprecate-merge/README.md
ember/5/deprecate-router-events/README.md
ember/5/ember-jquery-legacy/README.md
ember/5/fpe-computed/README.md
ember/5/fpe-observes/README.md
ember/5/fpe-on/README.md
ember/5/jquery-apis/README.md
ember/5/jquery-event/README.md
ember/5/notify-property-change/README.md
ember/5/object-new-constructor/README.md

based on https://github.com/ember-codemods/ember-3x-codemods#deprecations--transforms

INT-1755 Ember.js: Make precise applicability criteria version

---

ember/5/es5-getter-ember-codemod/README.md

ref: https://github.com/ember-codemods/es5-getter-ember-codemod

INT-1755 Doc for ES5 Getter Ember Codemod

---

ember/5/cp-property-map/README.md
ember/5/cp-property/README.md
ember/5/cp-volatile/README.md
ember/5/jquery-apis/README.md

1. cp-property
-   https://deprecations.emberjs.com/v3.x/#toc_computed-property-property
2. cp-property-map
-   https://deprecations.emberjs.com/v3.x/#toc_computed-property-property
3. cp-volatile
-   https://deprecations.emberjs.com/v3.x/#toc_computed-property-volatile
4. jquery-apis
-   https://deprecations.emberjs.com/v3.x/#toc_jquery-apis

INT-1755 Descriptions/links for cp-property, cp-volatile and more

---

next/13/replace-next-head/test.ts

https://linear.app/intuita/issue/INT-1797/restore-unit-tests-from-next-head-v1

restore old unit tests, remove useless tests, refactor tests

---

next/13/replace-next-head/index.ts

fix formattings

---

netlify-sdk/0.8.5/createEnvironmentVariable/README.md
netlify-sdk/0.8.5/createEnvironmentVariable/config.json
netlify-sdk/0.8.5/createEnvironmentVariable/index.ts
netlify-sdk/0.8.5/createEnvironmentVariable/test.ts
netlify-sdk/0.8.5/createOrUpdateVariable/README.md
netlify-sdk/0.8.5/createOrUpdateVariable/config.json
netlify-sdk/0.8.5/createOrUpdateVariable/index.ts
netlify-sdk/0.8.5/createOrUpdateVariables/README.md
netlify-sdk/0.8.5/createOrUpdateVariables/config.json
netlify-sdk/0.8.5/createOrUpdateVariables/index.ts
netlify-sdk/0.8.5/deleteEnvironmentVariable/README.md
netlify-sdk/0.8.5/deleteEnvironmentVariable/config.json
netlify-sdk/0.8.5/deleteEnvironmentVariable/index.ts
netlify-sdk/0.8.5/deleteEnvironmentVariables/README.md
netlify-sdk/0.8.5/deleteEnvironmentVariables/config.json
netlify-sdk/0.8.5/deleteEnvironmentVariables/index.ts
netlify-sdk/0.8.5/getEnvironmentVariables/README.md
netlify-sdk/0.8.5/getEnvironmentVariables/config.json
netlify-sdk/0.8.5/getEnvironmentVariables/index.ts
netlify-sdk/0.8.5/patchEnvironmentVariable/README.md
netlify-sdk/0.8.5/patchEnvironmentVariable/config.json
netlify-sdk/0.8.5/patchEnvironmentVariable/index.ts
netlify-sdk/0.8.5/updateEnvironmentVariable/README.md
netlify-sdk/0.8.5/updateEnvironmentVariable/config.json
netlify-sdk/0.8.5/updateEnvironmentVariable/index.ts

This PR includes all of the code mods to fix breaking 0.8.5 Netlify SDK updates

Codemods for Netlify SDK 0.8.5 breaking patterns (tests not yet added)

---

next/13/replace-next-head/index.ts
next/13/replace-next-head/test.ts

fix imports copied twice

---

i18n/index.ts
i18n/test.ts

- support getTextBody function
- support conditions and binary expr passed to `t` function

[codemod: cal.com/i18n]support getTextBody function

---

cal.com/app-directory-boilerplate-calcom/index.ts

INT-1970 App dir boilerplate calcom fix

---

cal.com/app-directory-boilerplate-calcom/index.ts

INT-1970 [cal.com-app-dir] Remove unnecessary tab space in `page.tsx`

---

next/13/app-directory-boilerplate/index.ts
next/13/app-directory-boilerplate/test.ts

closes https://linear.app/intuita/issue/INT-2076/[codemodfn-app-directory-boilerplate]-rootlayout-not-created-when

[CODEMOD:FN app-directory-boilerplate] RootLayout not created when project does not have _document file

---

next/13/remove-get-static-props/index.ts
next/13/remove-get-static-props/test.ts

int-2133-remove-get-static-props-add-utils
wip
wip
wip
update tests

int-2133-remove-get-static-props-add-utils

---

codemods/ember/5/no-implicit-this/src/index.js
codemods/intuita/migrate-codemod-registry/src/index.ts
codemods/msw/2/type-args/src/index.ts
codemods/next/13/remove-get-static-props/src/index.ts
codemods/next/13/replace-use-search-params/src/index.ts
ember/5/no-implicit-this/index.js
intuita/migrate-codemod-registry/index.ts
msw/2/type-args/index.ts
next/13/remove-get-static-props/index.ts
next/13/replace-use-search-params/index.ts

chore: remove-get-static-props, improve ADD_BUILD_LEGACY_CTX_UTIL_CONTENT
prettier

INT-2197 chore: remove-get-static-props, improve ADD_BUILD_LEGACY_CTX_UTIL_CONTENT

---

codemods/mocha/vitest/.mocharc.json
codemods/mocha/vitest/README.md
codemods/mocha/vitest/config.json
codemods/mocha/vitest/index.d.ts
codemods/mocha/vitest/package.json
codemods/mocha/vitest/src/index.ts
codemods/mocha/vitest/test/test.ts
codemods/mocha/vitest/tsconfig.json
pnpm-lock.yaml

I will work on ensuring the codemod not making empty lines.

INT-2311 Mocha -> Vitest codemod

---

.github/workflows/build.yml
codemods/mui/5/core-styles-import/README.md
readme-parser/parse.test.ts
readme-parser/parse.ts

commit created to website repo: https://github.com/intuita-inc/website/commit/6ad1698b0e392f6d33c5a45526f3a851f4341bdc

INT-2338 Fix readme-parser bugs

---

readme-parser/parse.test.ts
readme-parser/parse.ts
readme-parser/sync.ts

Quick fixes for the readme parser logic to run correctly on the main branch.

fix(parser): readme parser fixes
